### ISSUE TITLE
R-package download "Not found"

### ISSUE THREAD

**Issue by R-ramljak** [eurostat/Spatial-KWD#1]
I want to download the R-package, however the two links indicated in the Readme lead to a Github page saying "Not found". When trying to "Save the location" it downloads and empty .zip folder. Did possibly the link change?

**Comment by mmatyi** [comment]
Marco please use the 0.1.2 version from [here](https://github.com/eurostat/Spatial-KWD/releases/tag/v0.1.2-alpha).
`installr::install.packages.zip("https://github.com/eurostat/Spatial-KWD/releases/download/v0.1.2-alpha/SpatialKWD_0.1.2.zip")`
